version: "3.9"
services:
  yasgoldgallery:
    build:
      context: ./yasgoldgallery-ui
      dockerfile: Dockerfile
    container_name: yasgoldgallery
    restart: unless-stopped
    ports:
      - 80:80

networks:
  default:
    external:
      name: webtsNetwork